## importing numpy library

In [18]:
import numpy as np

In [19]:
np #an alias for refering numpy library it will now be recognized as numpy

<module 'numpy' from 'C:\\Users\\Durvankur Balkawade\\anaconda3\\lib\\site-packages\\numpy\\__init__.py'>

## Creating Numpy Array

In [20]:
x=np.array([1,2,3,4])
print(x)

[1 2 3 4]


## Creating a matrix


In [21]:
x=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [24]:
print(x)
x.shape

[[1 2 3]
 [4 5 6]
 [7 8 9]]


(3, 3)

In [25]:
x[0,1] #[row index,column index]

2

## Slicing

In [26]:
x[0:2,0:2]

array([[1, 2],
       [4, 5]])

In [27]:
x.shape

(3, 3)

In [28]:
z=np.array([[1,2,4],[6,7,5]])

In [29]:
z.shape #shape attribute returns a tuple with the dimensions of matrix or array

(2, 3)

## Accessing Column from the numpy array

In [30]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [31]:
##Accessing columns from the numpy array
x[:,0] #added : in row parameter bcz we want to access only the columns

array([1, 4, 7])

## Addition of two numpy arrays

In [39]:
a=np.array([[10,20,30],[40,50,60],[70,80,90]])

In [40]:
print(a)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [34]:
b=np.array([[2,4,5],[6,7,8],[11,12,13]])

In [35]:
print(b)

[[ 2  4  5]
 [ 6  7  8]
 [11 12 13]]


In [43]:
np.add(a,b)

array([[ 12,  24,  35],
       [ 46,  57,  68],
       [ 81,  92, 103]])

## Multiplication of two numpy arrays

In [44]:
np.dot(a,b)

array([[ 470,  540,  600],
       [1040, 1230, 1380],
       [1610, 1920, 2160]])

## Transpose of matrix

In [48]:
print(a) #original matrix a

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [45]:
np.transpose(a)

array([[10, 40, 70],
       [20, 50, 80],
       [30, 60, 90]])

In [49]:
print(b) #original matrix b

[[ 2  4  5]
 [ 6  7  8]
 [11 12 13]]


In [46]:
np.transpose(b)

array([[ 2,  6, 11],
       [ 4,  7, 12],
       [ 5,  8, 13]])

## creating zeros and ones

In [52]:
p=np.zeros((3,3))

In [53]:
print(p)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [60]:
type(p[0,1])

numpy.float64

In [61]:
n=np.ones((3,3))

In [62]:
print(n)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [63]:
type(n[0,1])

numpy.float64

In [70]:
m=np.zeros((3,3),dtype=int) #in dtype we can specify data type of matrix to print

In [71]:
print(m)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [72]:
d=np.ones((3,3),dtype=int)

In [73]:
print(d)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [78]:
m1=np.zeros((3,3) ,dtype=complex) #matrix of complex numbers

In [79]:
print(m1)

[[0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j]]
